-- MySQL Script generated by MySQL Workbench
-- 02/14/18 12:38:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BDProyectoMate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDProyectoMate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDProyectoMate` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BDProyectoMate` ;

-- -----------------------------------------------------
-- Table `BDProyectoMate`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProyectoMate`.`Area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `HoraEntrada` TIME NULL,
  `HoraSalida` TIME NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDProyectoMate`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProyectoMate`.`ADMIN` (
  `idAdmin` INT NOT NULL,
  `User` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDProyectoMate`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProyectoMate`.`Personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `DNI` INT NULL,
  `RUC` VARCHAR(12) NULL,
  `Area_idArea` INT NOT NULL,
  `Cargo` TINYINT(1) NULL,
  `ADMIN_idAdmin` INT NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersonal`, `Area_idArea`, `ADMIN_idAdmin`),
  INDEX `fk_Personal_Area1_idx` (`Area_idArea` ASC),
  INDEX `fk_Personal_ADMIN1_idx` (`ADMIN_idAdmin` ASC),
  CONSTRAINT `fk_Personal_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `BDProyectoMate`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personal_ADMIN1`
    FOREIGN KEY (`ADMIN_idAdmin`)
    REFERENCES `BDProyectoMate`.`ADMIN` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDProyectoMate`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProyectoMate`.`Registro` (
  `idRegistro` INT NOT NULL AUTO_INCREMENT,
  `-HoraRegistroIn` DATETIME NULL,
  `HoraRegistroOut` DATETIME NULL,
  `Personal_idPersonal` INT NOT NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idRegistro`),
  INDEX `fk_Registro_Personal_idx` (`Personal_idPersonal` ASC),
  CONSTRAINT `fk_Registro_Personal`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `BDProyectoMate`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
