/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BaseDatos.ConectorBD;
import Clases.Area;
import Clases.Fecha;
import Clases.GestionarArea;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamer
 */
public class GUIArea3 extends javax.swing.JFrame {

      private String accion ;
  /**
     * Creates new form GUIArea2
     */
      Area area = new Area();
      Fecha fecha = new Fecha();
      GestionarArea gestion = new GestionarArea();
      ConectorBD mysql = new ConectorBD();
      Connection cn= mysql.Conectar(); 
      PreparedStatement pst=null;
      ResultSet  rs=null;
  
    /**
     * Creates new form GUIArea3
     */
    public GUIArea3() {
        initComponents();
        deshabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        areaagregar = new javax.swing.JPanel();
        btnGuardarArea = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        areamodificar = new javax.swing.JPanel();
        btnModificar = new rojerusan.RSMaterialButtonRectangle();
        btnCancelModArea = new rojerusan.RSMaterialButtonRectangle();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtModHOut = new javax.swing.JTextField();
        txtModHIn = new javax.swing.JTextField();
        txtModNombre = new javax.swing.JTextField();
        areaeliminar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBusquedaArea = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNombArea = new javax.swing.JLabel();
        lblHoraIngreso = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        btnEliminarA = new rojerusan.RSMaterialButtonRectangle();
        btnCancelDeleteArea = new rojerusan.RSMaterialButtonRectangle();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(59, 89, 152));

        areaagregar.setBackground(new java.awt.Color(255, 255, 255));

        btnGuardarArea.setText("Guardar");
        btnGuardarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAreaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Hora de Entrada");

        jLabel3.setText("Hora de Salida");

        javax.swing.GroupLayout areaagregarLayout = new javax.swing.GroupLayout(areaagregar);
        areaagregar.setLayout(areaagregarLayout);
        areaagregarLayout.setHorizontalGroup(
            areaagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaagregarLayout.createSequentialGroup()
                .addGroup(areaagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areaagregarLayout.createSequentialGroup()
                        .addContainerGap(147, Short.MAX_VALUE)
                        .addGroup(areaagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(areaagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtEntrada)
                            .addComponent(txtHoraSalida)))
                    .addGroup(areaagregarLayout.createSequentialGroup()
                        .addContainerGap(276, Short.MAX_VALUE)
                        .addComponent(btnGuardarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        areaagregarLayout.setVerticalGroup(
            areaagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaagregarLayout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(areaagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(areaagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(areaagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnGuardarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanelSlider1.add(areaagregar, "card2");

        areamodificar.setBackground(new java.awt.Color(255, 255, 255));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelModArea.setText("CAncelar");
        btnCancelModArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelModAreaActionPerformed(evt);
            }
        });

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        jLabel9.setText("Hora de Entrada");

        jLabel10.setText("Hora de Salida");

        javax.swing.GroupLayout areamodificarLayout = new javax.swing.GroupLayout(areamodificar);
        areamodificar.setLayout(areamodificarLayout);
        areamodificarLayout.setHorizontalGroup(
            areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areamodificarLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areamodificarLayout.createSequentialGroup()
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btnCancelModArea, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(areamodificarLayout.createSequentialGroup()
                        .addGroup(areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addGroup(areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModNombre)
                            .addComponent(txtModHIn)
                            .addComponent(txtModHOut, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(232, 232, 232))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areamodificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        areamodificarLayout.setVerticalGroup(
            areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areamodificarLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(113, 113, 113)
                .addGroup(areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(92, 92, 92)
                .addGroup(areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtModHIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtModHOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(areamodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelModArea, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jPanelSlider1.add(areamodificar, "card3");

        areaeliminar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Area");

        jLabel6.setText("Hora de Ingreso");

        jLabel7.setText("Hora de salida");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminarA.setText("Eliminar");
        btnEliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAActionPerformed(evt);
            }
        });

        btnCancelDeleteArea.setText("Cancelar");
        btnCancelDeleteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDeleteAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout areaeliminarLayout = new javax.swing.GroupLayout(areaeliminar);
        areaeliminar.setLayout(areaeliminarLayout);
        areaeliminarLayout.setHorizontalGroup(
            areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaeliminarLayout.createSequentialGroup()
                .addGroup(areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areaeliminarLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnEliminarA, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(btnCancelDeleteArea, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(areaeliminarLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(areaeliminarLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(179, 179, 179)
                                .addGroup(areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHoraIngreso)
                                    .addComponent(lblNombArea)
                                    .addComponent(lblHoraSalida))))))
                .addGap(135, 135, 135))
            .addGroup(areaeliminarLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(txtBusquedaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(101, 101, 101))
        );
        areaeliminarLayout.setVerticalGroup(
            areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaeliminarLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(68, 68, 68)
                .addGroup(areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNombArea))
                .addGap(69, 69, 69)
                .addGroup(areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblHoraIngreso))
                .addGap(73, 73, 73)
                .addGroup(areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblHoraSalida))
                .addGap(117, 117, 117)
                .addGroup(areaeliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelDeleteArea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanelSlider1.add(areaeliminar, "card4");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/areatrabajoimg.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editararea.png"))); // NOI18N
        jButton1.setText("Modifcar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregararea.png"))); // NOI18N
        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backbuton.png"))); // NOI18N
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminararea.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanelSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(20, areaagregar, jPanelSlider1.right);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(20, areamodificar, jPanelSlider1.right);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(20, areaeliminar, jPanelSlider1.right);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Seleccionador c= new Seleccionador();
        c.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnGuardarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAreaActionPerformed
        // TODO add your handling code here:

        area.setNombre(txtNombre.getText());

        area.setHoraIn(txtEntrada.getText());
        area.setHoraOut(txtHoraSalida.getText());

        accion = "guardar";

        if (accion.equals("guardar")) {
            if (gestion.registar(area)) {
                JOptionPane.showMessageDialog(rootPane, "EL area fue registrada correctamente");
            }
        } else{
            JOptionPane.showMessageDialog(rootPane, "No se pudo realizar el registro");
        }

    }//GEN-LAST:event_btnGuardarAreaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String nombre = txtSearch.getText();
        area.setNombre(txtModNombre.getText());
        area.setHoraIn(txtModHIn.getText());
        area.setHoraOut(txtModHOut.getText());

        accion="Modificar";
        System.out.println("error 1");
        if (accion.equals("Modificar")) {
            System.out.println("error 2");
            if (gestion.actualizar(nombre,area)) {
                System.out.println("error 3");
                JOptionPane.showMessageDialog(rootPane, "EL area  pudo ser modificada correctamente");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudo modificar el area");
                System.out.println("error 5");
            }
        } else{
            JOptionPane.showMessageDialog(rootPane, "No se puede acceder al area");
            System.out.println("error 5");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String nombre = txtSearch.getText();
        
        boolean busq= gestion.buscar(nombre);
        if(busq == true){
            habilitar();
        String data = null;
        String hout=null,hin=null;
        String sSQL="SELECT * FROM bdproyectomate.area where Nombre= ?" ;
        try {
            pst =cn.prepareStatement(sSQL);
            pst.setString(1, nombre);
            rs =pst.executeQuery();
            while(rs.next()){
                if(rs != null){
                    data = rs.getString("Nombre");
                    hin= rs.getString("HoraEntrada");
                    hout=rs.getString("HoraSalida");
                    //
                    txtModNombre.setText(data);
                    txtModHIn.setText(hin);
                    txtModHOut.setText(hout);
                }
                if(rs == null){
                    JOptionPane.showMessageDialog(null,"EL area buscada no existe ");
                    txtModNombre.setText(null);
                    txtModHIn.setText(null);
                    txtModHOut.setText(null);

                }
                pst.close();
            }

        } catch (SQLException | HeadlessException e) {
            System.out.println(e);
        }
      }else{
            JOptionPane.showMessageDialog(null,"El Area buscada no se encuentra registrada ");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String nombre = txtBusquedaArea.getText();
        
        boolean busdel = gestion.buscar(nombre);
        if(busdel == true){
        String data = null;
        String hout=null,hin=null;
        String sSQL="SELECT * FROM bdproyectomate.area where Nombre= ?" ;
        try {
            pst =cn.prepareStatement(sSQL);
            pst.setString(1, nombre);
            rs =pst.executeQuery();
            while(rs.next()){
                if(rs != null){
                    data = rs.getString("Nombre");
                    hin= rs.getString("HoraEntrada");
                    hout=rs.getString("HoraSalida");
                    //
                    lblNombArea.setText(data);
                    lblHoraIngreso.setText(hin);
                    lblHoraSalida.setText(hout);
                }
                if(rs == null){
                    JOptionPane.showMessageDialog(null,"EL area buscada no existe ");
                    lblNombArea.setText(null);
                    lblHoraIngreso.setText(null);
                    lblHoraSalida.setText(null);

                }
                pst.close();
            }

        } catch (SQLException | HeadlessException e) {
            System.out.println(e);
        }
        }else{
            JOptionPane.showMessageDialog(null,"El Area buscada no se encuentra registrada");
        } 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAActionPerformed
        // TODO add your handling code here:
        String nombre = txtBusquedaArea.getText();
        int id = gestion.ID(nombre);
        if(id > 0){
            
            int resp=JOptionPane.showConfirmDialog(null,"¿Desea eliminar el Area seleccionada?");
            if (JOptionPane.OK_OPTION == resp){
                if(gestion.eliminar(nombre)== true ){

                    JOptionPane.showMessageDialog(null,"Se elimino el Area con exito");

                }else{
                    JOptionPane.showMessageDialog(null,"No se ha podido eliminar el Area");
                }

            } else{
                JOptionPane.showMessageDialog(null, "No selecciono una opción afirmativa");

            }

        }else{
            System.out.println("no hay nada ");
        }
    }//GEN-LAST:event_btnEliminarAActionPerformed

    private void btnCancelModAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelModAreaActionPerformed
        // TODO add your handling code here:
        limpiar();
        deshabilitar();
    }//GEN-LAST:event_btnCancelModAreaActionPerformed

    private void btnCancelDeleteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDeleteAreaActionPerformed
        // TODO add your handling code here:
        limpiar();
        
    }//GEN-LAST:event_btnCancelDeleteAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIArea3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIArea3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIArea3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIArea3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIArea3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaagregar;
    private javax.swing.JPanel areaeliminar;
    private javax.swing.JPanel areamodificar;
    private javax.swing.JButton btnBuscar;
    private rojerusan.RSMaterialButtonRectangle btnCancelDeleteArea;
    private rojerusan.RSMaterialButtonRectangle btnCancelModArea;
    private rojerusan.RSMaterialButtonRectangle btnEliminarA;
    private rojerusan.RSMaterialButtonRectangle btnGuardarArea;
    private rojerusan.RSMaterialButtonRectangle btnModificar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JLabel lblHoraIngreso;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblNombArea;
    private javax.swing.JTextField txtBusquedaArea;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtModHIn;
    private javax.swing.JTextField txtModHOut;
    private javax.swing.JTextField txtModNombre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
void habilitar(){
    txtModNombre.setEnabled(true);
    txtModHIn.setEnabled(true);
    txtModHOut.setEnabled(true);
    txtModNombre.setText("");
    txtModHIn.setText("");
    txtModHOut.setText("");
}
void deshabilitar(){
    txtModNombre.setEnabled(false);
    txtModHIn.setEnabled(false);
    txtModHOut.setEnabled(false);
    txtModNombre.setText("");
    txtModHIn.setText("");
    txtModHOut.setText("");
}

void limpiar(){
    
    txtModNombre.setText("");
    txtModHIn.setText("");
    txtModHOut.setText("");
    txtSearch.setText("");
    lblNombArea.setText(null);
    lblHoraIngreso.setText(null);
    lblHoraSalida.setText(null);
   txtBusquedaArea.setText("");
}

}

