    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BaseDatos.ConectorBD;
import BaseDatos.Estados;
import Clases.AgregarPersonal;
import Clases.Area;
import Clases.LimitadorCaracteres;
import Clases.Personal;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gamer
 */
public class Seleccion2 extends javax.swing.JFrame {

    /**
     * Creates new form Seleccion2
     */
    private String accion = "agregar";
    private DefaultComboBoxModel modelocombo;
   
    DefaultTableModel modelotabla;
    Area area = new Area();
    Personal persona = new Personal();       
    AgregarPersonal agregar = new AgregarPersonal();  
    ConectorBD mysql = new ConectorBD();
    Connection cn= mysql.Conectar(); 
    PreparedStatement pst=null;
     ResultSet  rs=null;
    public Seleccion2() {
         modelocombo = new DefaultComboBoxModel(new String[]{});

        initComponents();
        deshabilitar();
        this.setLocationRelativeTo(null);
        jPanelSlider1.nextPanel(1, panelagregar, jPanelSlider1.left);
      
         txtDNI.setDocument(new LimitadorCaracteres(txtDNI,8));
         txtRUC.setDocument(new LimitadorCaracteres(txtRUC,11));
        Estados cc = new Estados();
        DefaultComboBoxModel modeloEstad = new DefaultComboBoxModel( cc.mostrarEstados());
        CombArea.setModel(modeloEstad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btonagregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        panelmodificar = new javax.swing.JPanel();
        btnModPersonal = new rojerusan.RSMaterialButtonRectangle();
        btnCancelModPersonal = new rojerusan.RSMaterialButtonRectangle();
        txtBusNomb = new javax.swing.JTextField();
        btnBMod = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtModApellido = new javax.swing.JTextField();
        txtMoDNI = new javax.swing.JTextField();
        txtModNombre = new javax.swing.JTextField();
        txtModRUC = new javax.swing.JTextField();
        txtModCargo = new javax.swing.JTextField();
        txtModArea = new javax.swing.JTextField();
        paneleliminar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtBusquedaDNI = new javax.swing.JTextField();
        btnBuscarEliminar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelDeletePersonal = new rojerusan.RSMaterialButtonRectangle();
        btnEliminarPersonal = new rojerusan.RSMaterialButtonRectangle();
        lblNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JTextField();
        lblDNI = new javax.swing.JTextField();
        lblRUC = new javax.swing.JTextField();
        lblArea = new javax.swing.JTextField();
        lblCargo = new javax.swing.JTextField();
        panelagregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        btnCancelar = new rojerusan.RSMaterialButtonRectangle();
        btnAgregar = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();
        CombArea = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(59, 89, 152));

        btonagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_check.png"))); // NOI18N
        btonagregar.setText("Agregar");
        btonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonagregarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_admin.png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_delete.png"))); // NOI18N
        jButton11.setText("Eliminar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/admin2.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backbuton.png"))); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(btonagregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btonagregar)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addGap(32, 32, 32)
                .addComponent(jButton11)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelmodificar.setBackground(new java.awt.Color(255, 255, 255));

        btnModPersonal.setText("Modificar");
        btnModPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPersonalActionPerformed(evt);
            }
        });

        btnCancelModPersonal.setText("Cancelar");
        btnCancelModPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelModPersonalActionPerformed(evt);
            }
        });

        btnBMod.setText("Buscar");
        btnBMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBModActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        jLabel9.setText("Apellido");

        jLabel10.setText("Area");

        jLabel11.setText("DNI");

        jLabel18.setText("RUC");

        jLabel19.setText("Cargo");

        txtModCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmodificarLayout = new javax.swing.GroupLayout(panelmodificar);
        panelmodificar.setLayout(panelmodificarLayout);
        panelmodificarLayout.setHorizontalGroup(
            panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmodificarLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(btnModPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnCancelModPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(panelmodificarLayout.createSequentialGroup()
                .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelmodificarLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(txtBusNomb, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBMod))
                    .addGroup(panelmodificarLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(txtModArea, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelmodificarLayout.createSequentialGroup()
                    .addGap(158, 158, 158)
                    .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10))
                    .addGap(73, 73, 73)
                    .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtModApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(txtModCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(txtModRUC, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(txtMoDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(txtModNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addContainerGap(158, Short.MAX_VALUE)))
        );
        panelmodificarLayout.setVerticalGroup(
            panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmodificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusNomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBMod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addComponent(txtModArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelModPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelmodificarLayout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(txtModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelmodificarLayout.createSequentialGroup()
                            .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelmodificarLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel11))
                                .addGroup(panelmodificarLayout.createSequentialGroup()
                                    .addComponent(txtModApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)
                            .addComponent(jLabel18))
                        .addComponent(txtModRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(panelmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtModCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel10)
                    .addContainerGap(176, Short.MAX_VALUE)))
        );

        jPanelSlider1.add(panelmodificar, "card3");

        paneleliminar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Buscar");

        btnBuscarEliminar.setText("Buscar");
        btnBuscarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEliminarActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre");

        jLabel14.setText("Apellido");

        jLabel15.setText("DNI");

        jLabel16.setText("Cargo");

        jLabel17.setText("Area");

        jLabel7.setText("RUC");

        btnCancelDeletePersonal.setText("Cancelar");
        btnCancelDeletePersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDeletePersonalActionPerformed(evt);
            }
        });

        btnEliminarPersonal.setText("Eliminar");
        btnEliminarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneleliminarLayout = new javax.swing.GroupLayout(paneleliminar);
        paneleliminar.setLayout(paneleliminarLayout);
        paneleliminarLayout.setHorizontalGroup(
            paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneleliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelDeletePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(paneleliminarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel7))
                .addGap(117, 117, 117)
                .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(lblDNI)
                    .addComponent(lblRUC)
                    .addComponent(lblArea)
                    .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneleliminarLayout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jLabel12)
                    .addGap(63, 63, 63)
                    .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarEliminar)
                    .addGap(92, 92, 92)))
            .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneleliminarLayout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(btnEliminarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );
        paneleliminarLayout.setVerticalGroup(
            paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleliminarLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneleliminarLayout.createSequentialGroup()
                        .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneleliminarLayout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneleliminarLayout.createSequentialGroup()
                        .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneleliminarLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(34, 34, 34))
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel17)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(btnCancelDeletePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneleliminarLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtBusquedaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarEliminar))
                    .addContainerGap(494, Short.MAX_VALUE)))
            .addGroup(paneleliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneleliminarLayout.createSequentialGroup()
                    .addContainerGap(487, Short.MAX_VALUE)
                    .addComponent(btnEliminarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );

        jPanelSlider1.add(paneleliminar, "card4");

        panelagregar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("DNI");

        jLabel5.setText("RUC");

        jLabel6.setText("Cargo");

        btnCancelar.setText("Cancelar");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Area");

        CombArea.setModel(modelocombo);

        javax.swing.GroupLayout panelagregarLayout = new javax.swing.GroupLayout(panelagregar);
        panelagregar.setLayout(panelagregarLayout);
        panelagregarLayout.setHorizontalGroup(
            panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelagregarLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(panelagregarLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(73, 73, 73)
                .addGroup(panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CombArea, 0, 228, Short.MAX_VALUE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(txtRUC, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelagregarLayout.setVerticalGroup(
            panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelagregarLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelagregarLayout.createSequentialGroup()
                        .addGroup(panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelagregarLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4))
                            .addGroup(panelagregarLayout.createSequentialGroup()
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(CombArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(panelagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jPanelSlider1.add(panelagregar, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonagregarActionPerformed
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(20, panelagregar, jPanelSlider1.right);
    }//GEN-LAST:event_btonagregarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jPanelSlider1.nextPanel(20, panelmodificar, jPanelSlider1.right);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(20, paneleliminar, jPanelSlider1.right);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Seleccionador c= new Seleccionador();
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
         
       persona.setNombre(txtNombre.getText());
        persona.setApellidos(txtApellido.getText());
        persona.setDni(Integer.parseInt(txtDNI.getText()));
        persona.setRuc(txtRUC.getText());
     //   persona.setCargo(txtCargo.getText());
       // int i = CombArea.getSelectedIndex();
      Estados est = (Estados)CombArea.getSelectedItem();
      int es= est.getId(); 
     
      if(CombArea.getSelectedIndex()>1 ){
          persona.setIdArea(es);
      }    
     
           
      persona.setPermisosAdmin(1);
        
        if((txtCargo.getText()).equals("empleado") ||(txtCargo.getText()).equals("Empleado") ){
           persona.setCargo(false);
        }else{
            persona.setCargo(true);
        }
        
        if (accion.equals("agregar")) {
            
             if(CombArea.getSelectedIndex()==0 ){
                   JOptionPane.showMessageDialog(rootPane, "Seleccione una opcion");
             }else{
                  if (agregar.registrar(persona)){
                    JOptionPane.showMessageDialog(rootPane, "El personal fue registrado correctamente"); 
                  }
             }      
         }else{
                    JOptionPane.showMessageDialog(rootPane,"No se puede registrar a el personal");
         }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEliminarActionPerformed
        String buscar = txtBusquedaDNI.getText();
        int dni = Integer.parseInt(buscar);
//        if(agregar.buscar(dni)== true){
//            System.out.println("se pudo realizar la busqueda");
//        }else{
//            System.out.println("nop ");
//        }
       int busqdni = agregar.ID(dni);
       if(busqdni>0){
        String nomb=null,apellido=null;
        int are=0,cargo,ruc=0,d;
       String c =null,ar=null,p=null;
        String sSQL="select * from bdproyectomate.personal where DNI= "+dni;
        try {
            pst =cn.prepareStatement(sSQL);
            rs =pst.executeQuery();
            while(rs.next()){
                if(rs != null){
                   nomb=rs.getString("Nombre");
                    System.out.println(nomb);
                  d=rs.getInt("DNI");
                  String dn = Integer.toString(d);
                    System.out.println("dni"+dn);
                 String ru=rs.getString("RUC");
                    System.out.println("ruc"+ru);
                //String ru = Integer.toString(ruc);
                 are=rs.getInt("Area_idArea"); 
                    System.out.println("area:" + are);
                 cargo=rs.getInt("Cargo");
                  if(cargo == 0){
                      c="Empleado";
                  }else{
                      c="Administrador";
                  }
                    System.out.println("cargo :"+c);
                 apellido=rs.getString("apellidos");
                    System.out.println("apellidos:" +   apellido);
////                  String a = area.getNombre();                
                //  p=rs.getString(a);             
                lblNombre.setText(nomb);
                lblApellido.setText(apellido);
        
                lblDNI.setText(dn);
                lblRUC.setText(ru);
              lblArea.setText(Integer.toString(are));
                 lblCargo.setText(c);
                }
                if(rs == null){                    
                    }
                pst.close();
            }    
         } catch (SQLException | HeadlessException e) {
             System.out.println(e);
         }         
       }else{
           JOptionPane.showMessageDialog(null,"El DNI ingresado no se encuentra registrado");
       }
    }//GEN-LAST:event_btnBuscarEliminarActionPerformed

    private void btnEliminarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonalActionPerformed
        // TODO add your handling code here:
        
         String nombre = txtBusquedaDNI.getText();
        int id = Integer.parseInt(nombre);
        if(id > 0){
            //System.out.println("encontro algo");
            //   JOptionPane.showConfirmDialog(null, "¿Desea eliminar este Area?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            int resp=JOptionPane.showConfirmDialog(null,"¿Desea eliminar el Area seleccionada?");
            if (JOptionPane.OK_OPTION == resp){
               
                try {
                    if(agregar.eliminar(id, persona)== true ){
                        
                        JOptionPane.showMessageDialog(null,"Se elimino el Area con exito");
                        
                    }else{
                        JOptionPane.showMessageDialog(null,"No se ha podido eliminar el Area");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Seleccion2.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            } else{
                JOptionPane.showMessageDialog(null, "No selecciono una opción afirmativa");
                             
            }

        }else{
            System.out.println("no hay nada ");
        }


        
            
    }//GEN-LAST:event_btnEliminarPersonalActionPerformed


    private void btnBModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBModActionPerformed

        // TODO add your handling code here:
        String buscar = txtBusNomb.getText();
        int dni = Integer.parseInt(buscar);
        int busq = agregar.ID(dni);
        if(busq >0){
            habilitar();
        String nomb=null,apellido=null;
        int are=0,cargo,ruc=0,d;
       String c =null,ar=null,p=null;
        String sSQL="select * from bdproyectomate.personal where DNI= "+dni;
        try {
            pst =cn.prepareStatement(sSQL);
            rs =pst.executeQuery();
            while(rs.next()){
                if(rs != null){
                   nomb=rs.getString("Nombre");
                    System.out.println(nomb);
                  d=rs.getInt("DNI");
                  String dn = Integer.toString(d);
                    System.out.println("dni"+dn);
                 String ru=rs.getString("RUC");
                    System.out.println("ruc"+ru);
                //String ru = Integer.toString(ruc);
                 are=rs.getInt("Area_idArea"); 
                    System.out.println("area:" + are);
                 cargo=rs.getInt("Cargo");
                  if(cargo == 0){
                      c="Empleado";
                  }else{
                      c="Administrador";
                  }
                    System.out.println("cargo :"+c);
                 apellido=rs.getString("apellidos");
                    System.out.println("apellidos:" +   apellido);
////                  String a = area.getNombre();                
                //  p=rs.getString(a);             
                txtModNombre.setText(nomb);
                txtModApellido.setText(apellido);
        
                txtMoDNI.setText(dn);
                txtModRUC.setText(ru);
                txtModArea.setText(Integer.toString(are));
              txtModCargo.setText(c);
                }
                if(rs == null){                    
                    }
                pst.close();
            }    
         } catch (SQLException | HeadlessException e) {
             System.out.println(e);
         }         
        }else{
             JOptionPane.showMessageDialog(null,"El personal que busca no ha sido registrado");
        }
        

    }//GEN-LAST:event_btnBModActionPerformed

    private void btnModPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPersonalActionPerformed
        // TODO add your handling code here:
     String buscar = txtBusNomb.getText();
       int dni = Integer.parseInt(buscar);
        int buscado = agregar.ID(dni);
        if(buscado>0){
        persona.setNombre(txtModNombre.getText());
       persona.setApellidos( txtModApellido.getText());
        String d = txtMoDNI.getText();
        int dn = Integer.parseInt(d);
        persona.setDni(dn);
        persona.setRuc(txtModRUC.getText());
//       String a = txtModArea.getText();
//       int ar=Integer.parseInt(a);
       persona.setIdArea(Integer.parseInt(txtModArea.getText()));
       persona.setPermisosAdmin(1);
       if((txtModCargo.getText()).equals("empleado") ||(txtModCargo.getText()).equals("Empleado") ){
           persona.setCargo(false);
        }else{
            persona.setCargo(true);
        }
        
//        
////        //        
////        
        accion="Modificar";
        System.out.println("error 1");
         if (accion.equals("Modificar")) {
            System.out.println("error 2");
            if (agregar.updateSalida(dni, persona)) {
                System.out.println("error 3");
                JOptionPane.showMessageDialog(rootPane, "EL personal   pudo ser modificada correctamente");
            }else{
                 JOptionPane.showMessageDialog(rootPane, "No se pudo modificar al personal");
                 System.out.println("error 5");
            }
        } else{
             JOptionPane.showMessageDialog(rootPane, "No se puede acceder al personal ");
             System.out.println("error 5");
         }

        }else{
            JOptionPane.showMessageDialog(null, "El DNI ingresado no se encuentra registrado");
        }
    }//GEN-LAST:event_btnModPersonalActionPerformed

    private void txtModCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModCargoActionPerformed

    private void btnCancelDeletePersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDeletePersonalActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCancelDeletePersonalActionPerformed

    private void btnCancelModPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelModPersonalActionPerformed
        // TODO add your handling code here:
        limpiar();
        deshabilitar();
        
    }//GEN-LAST:event_btnCancelModPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CombArea;
    private rojerusan.RSMaterialButtonRectangle btnAgregar;
    private javax.swing.JButton btnBMod;
    private javax.swing.JButton btnBuscarEliminar;
    private rojerusan.RSMaterialButtonRectangle btnCancelDeletePersonal;
    private rojerusan.RSMaterialButtonRectangle btnCancelModPersonal;
    private rojerusan.RSMaterialButtonRectangle btnCancelar;
    private rojerusan.RSMaterialButtonRectangle btnEliminarPersonal;
    private rojerusan.RSMaterialButtonRectangle btnModPersonal;
    private javax.swing.JButton btonagregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JTextField lblApellido;
    private javax.swing.JTextField lblArea;
    private javax.swing.JTextField lblCargo;
    private javax.swing.JTextField lblDNI;
    private javax.swing.JTextField lblNombre;
    private javax.swing.JTextField lblRUC;
    private javax.swing.JPanel panelagregar;
    private javax.swing.JPanel paneleliminar;
    private javax.swing.JPanel panelmodificar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBusNomb;
    private javax.swing.JTextField txtBusquedaDNI;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtMoDNI;
    private javax.swing.JTextField txtModApellido;
    private javax.swing.JTextField txtModArea;
    private javax.swing.JTextField txtModCargo;
    private javax.swing.JTextField txtModNombre;
    private javax.swing.JTextField txtModRUC;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRUC;
    // End of variables declaration//GEN-END:variables

void habilitar(){
 txtModNombre.setEnabled(true);
 txtModApellido.setEnabled(true);
 txtMoDNI.setEnabled(true);
 txtModRUC.setEnabled(true);
 txtModCargo.setEnabled(true);
 txtModArea.setEnabled(true);
 txtModNombre.setText("");
 txtModApellido.setText("");
 txtMoDNI.setText("");
 txtModRUC.setText("");
 txtModCargo.setText("");
 txtModArea.setText("");
 
 lblNombre.setEnabled(true);
 lblApellido.setEnabled(true);       
 lblDNI.setEnabled(true);
 lblRUC.setEnabled(true);
 lblArea.setEnabled(true);
 lblCargo.setEnabled(true);

  lblNombre.setText("");
 lblApellido.setText("");       
 lblDNI.setText("");
 lblRUC.setText("");
 lblArea.setText("");
 lblCargo.setText("");
}

 void deshabilitar(){
 txtModNombre.setEnabled(false);
 txtModApellido.setEnabled(false);
 txtMoDNI.setEnabled(false);
 txtModRUC.setEnabled(false);
 txtModCargo.setEnabled(false);
  txtModArea.setEnabled(false);
  lblNombre.setEnabled(false);
 lblApellido.setEnabled(false);       
 lblDNI.setEnabled(false);
 lblRUC.setEnabled(false);
 lblArea.setEnabled(false);
 lblCargo.setEnabled(false);

  lblNombre.setText("");
 lblApellido.setText("");       
 lblDNI.setText("");
 lblRUC.setText("");
 lblArea.setText("");
 lblCargo.setText("");
 txtModNombre.setText("");
 txtModApellido.setText("");
 txtMoDNI.setText("");
 txtModRUC.setText("");
 txtModCargo.setText("");
 txtModArea.setText("");
}
public void limpiar(){
 txtModNombre.setText("");
 txtModApellido.setText("");
 txtMoDNI.setText("");
 txtModRUC.setText("");
 txtModCargo.setText("");
 txtModArea.setText("");
 lblNombre.setText("");
 lblApellido.setText("");       
 lblDNI.setText("");
 lblRUC.setText("");
 lblArea.setText("");
 lblCargo.setText("");
 txtBusquedaDNI.setText("");
 txtBusNomb.setText("");
}

}
